apiVersion: apps/v1
kind: Deployment
metadata:
  name: myapp
  namespace: default
spec:
  selector:
    matchLabels:
      app: myapp
  template:
    metadata:
      labels:
        app: myapp
    spec:
      containers:
      - name: myapp
        image: fabiuse/reactdocker:latest
        resources:
          limits:
            memory: "128Mi"
            cpu: "500m"
        ports:
        - containerPort: 8080

---
apiVersion: v1
kind: Service
metadata:
  name: service
  namespace: default
spec:
  selector:
    app: Service
  ports:
  - port: 8080
---
apiVersion: v1
kind: Service
metadata:
  name: loadbalancer
  namespace: default
spec:
  type: LoadBalancer
  ports:
  - port: 80
  selector:
    app: LoadBalancer
